//PROJECT ON QUIZ GAME
#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
cout<<"\n Are you ready to play?";
getch();
cout<<"\n Rules are as follows:";
cout<<"\n 1. There will be a total of 10 questions.";
cout<<"\n 2. You will be given four options.";
cout<<"\n 3. On choosing the correct option, you get 5 points. Incorrect gets 0";
cout<<"\n 4. Team with maximum score wins.";

